name: 'Terraform-Dataabricks'

on:
  workflow_dispatch:
      
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@main
        
    - name: update file and push to remote
      run: |
         echo "Test push commit to the remote in the workflow" >> test.txt
         echo "Test push commit to the remote in the workflow" >> test2.txt
         echo "Test push commit to the remote in the workflow" >> test1.txt
         git config --global user.name "ikramshahbaz"
         git config --global user.email "ikramshahbaz@gmail.com"
         git add -A
         git commit -m "Update test.txt"
         git push

